name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            file1.tex
            file2.tex
            file3.tex
          working_directory:
            examples
          latexmk_use_xelatex: true
      - uses: fregante/setup-git-user@v1
      - name: Upload PDF to examples/
        run: |
          git pull origin gh-pages
          git checkout -b gh-pages
          git add *.pdf
          git commit -m "ci: Update example PDFs."
          git push origin gh-pages
